# Generated by Django 4.2.4 on 2023-08-21 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='customerName',
            new_name='customer_name',
        ),
    ]
